### ISSUE TITLE
syncData同步玩家数据返回的理智存在不准确的问题

### ISSUE THREAD

**Issue by Cai-Zhenhui** [djkcyl/py_arknights#2]
./arknights/cgi.py中
AkCall.Account.syncData()方法同步玩家数据返回数据中的理智值，存在不准确的问题。

**Comment by djkcyl** [comment]
这个或许是鹰角的问题，与请求库无关

**Comment by thesadru** [comment]
I believe you have to calculate your real sanity value with `last_ap_add_time`.

**Comment by Cai-Zhenhui** [comment]
> I believe you have to calculate your real sanity value with `lastApAddTime`.

AMAZE！
Thanks for sharing the information.
